### ISSUE TITLE
General comments on readability

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/quantum#1]
@samadammeek I think there should be:
1. An explanation of NP-Hard or NP-Complete or N-NP. You cannot assume readers have a mathematical background.
2. I suggest that `heterogony` is replaced with `heterogeneity`. The former seems to be mainly a biological term. If you keep it, I suggest a link to https://en.wikipedia.org/wiki/Heterogony_of_ends. Typo in PDF `hetrogeny`
3. After `quadratic rather than exponential` add `scaling of the problem size` 
4. `C and d` -> `C and D` ?
5. `down select` rephrase to `filter` ?
6.  A list of acronyms and their expansion.

I couldn't load the PDF: `Unable to render code block`. Downloaded and readable on my browser.

Good paper!

**Comment by samadammeek** [comment]
Thanks Chris, comments incorporated
